#!/usr/bin/env python3
"""Build a compact bundled TS file of NYC City Council District boundaries.

Source: NYC Open Data — City Council Districts (resource 872g-cjhh), EPSG:4326
GeoJSON. The raw export is ~3.8 MB of detailed MultiPolygons; this script keeps
the single largest ring per district and simplifies it with Ramer-Douglas-Peucker
so the bundle stays small while remaining geographically recognizable.

This is real NYC geography (council districts — the operational, ward-like unit),
never Toronto and never Brampton. Output mirrors src/data/nycBoroughBoundaries.ts.

Usage:
  curl -sL "https://data.cityofnewyork.us/api/geospatial/872g-cjhh?method=export&format=GeoJSON" -o /tmp/ccd.geojson
  python3 scripts/build_nyc_council_district_boundaries.py /tmp/ccd.geojson src/data/nycCouncilDistrictBoundaries.ts
"""
import json
import sys


def rdp(points, eps):
    """Ramer-Douglas-Peucker polyline simplification (lng/lat degrees)."""
    if len(points) < 3:
        return points
    dmax, idx = 0.0, 0
    a, b = points[0], points[-1]
    for i in range(1, len(points) - 1):
        d = _perp(points[i], a, b)
        if d > dmax:
            dmax, idx = d, i
    if dmax > eps:
        left = rdp(points[: idx + 1], eps)
        right = rdp(points[idx:], eps)
        return left[:-1] + right
    return [a, b]


def _perp(p, a, b):
    (x, y), (x1, y1), (x2, y2) = p, a, b
    dx, dy = x2 - x1, y2 - y1
    if dx == 0 and dy == 0:
        return ((x - x1) ** 2 + (y - y1) ** 2) ** 0.5
    t = ((x - x1) * dx + (y - y1) * dy) / (dx * dx + dy * dy)
    t = max(0.0, min(1.0, t))
    px, py = x1 + t * dx, y1 + t * dy
    return ((x - px) ** 2 + (y - py) ** 2) ** 0.5


def ring_area(ring):
    """Absolute planar area of a closed ring (shoelace, in deg^2)."""
    s = 0.0
    for i in range(len(ring) - 1):
        x1, y1 = ring[i]
        x2, y2 = ring[i + 1]
        s += x1 * y2 - x2 * y1
    return abs(s) / 2.0


def largest_ring(geometry):
    """Return the single largest outer ring across a (Multi)Polygon."""
    rings = []
    if geometry["type"] == "Polygon":
        rings = [geometry["coordinates"][0]]
    elif geometry["type"] == "MultiPolygon":
        rings = [poly[0] for poly in geometry["coordinates"]]
    if not rings:
        return None
    return max(rings, key=ring_area)


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "/tmp/ccd.geojson"
    out = sys.argv[2] if len(sys.argv) > 2 else "src/data/nycCouncilDistrictBoundaries.ts"
    eps = float(sys.argv[3]) if len(sys.argv) > 3 else 0.0006

    fc = json.load(open(src))
    records = []
    for feat in fc["features"]:
        dist = int(str(feat["properties"]["coundist"]).strip())
        ring = largest_ring(feat["geometry"])
        if not ring:
            continue
        pts = [[round(float(x), 4), round(float(y), 4)] for x, y in ring]
        simplified = rdp(pts, eps)
        if simplified[0] != simplified[-1]:
            simplified.append(simplified[0])
        records.append((dist, simplified))

    records.sort(key=lambda r: r[0])

    lines = []
    lines.append(
        "// Real NYC City Council District boundaries — the operational, ward-like\n"
        "// geographic unit for the NYC 311 workload heat map (boroughs are the broader\n"
        "// executive overview). Source: NYC Open Data — City Council Districts\n"
        "// (resource 872g-cjhh), EPSG:4326 GeoJSON, reduced to the largest ring per\n"
        "// district and simplified (Ramer-Douglas-Peucker) to keep the bundle small\n"
        "// while staying recognizable. Real NYC geography — never Toronto, never\n"
        "// Brampton. Generated by scripts/build_nyc_council_district_boundaries.py.\n"
    )
    lines.append("export type NYCCouncilDistrictBoundaryRecord = {")
    lines.append("  /** NYC City Council district number (1–51). Joins to v_nyc_council_district_workload.area. */")
    lines.append("  council_district: number")
    lines.append("  /** Short label rendered on the map polygon. */")
    lines.append("  short_label: string")
    lines.append("  geojson_geometry: { type: 'Polygon'; coordinates: number[][][] }")
    lines.append("}")
    lines.append("")
    lines.append("export const NYC_COUNCIL_DISTRICT_BOUNDARIES: NYCCouncilDistrictBoundaryRecord[] = [")
    for dist, ring in records:
        coords = "[" + ",".join("[" + str(x) + "," + str(y) + "]" for x, y in ring) + "]"
        lines.append("  {")
        lines.append(f"    council_district: {dist},")
        lines.append(f'    short_label: "{dist}",')
        lines.append(f"    geojson_geometry: {{ type: 'Polygon', coordinates: [{coords}] }},")
        lines.append("  },")
    lines.append("]")
    lines.append("")

    open(out, "w").write("\n".join(lines))
    pts_total = sum(len(r) for _, r in records)
    print(f"wrote {out}: {len(records)} districts, {pts_total} points")


if __name__ == "__main__":
    main()
